name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["kepler/lib", "kepler", "kepler/sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler
        
    - name: Build 
      working-directory: ${{ matrix.pkg }}
      run: cargo build --verbose

    - name: Run tests
      working-directory: ${{ matrix.pkg }}
      run: cargo test --verbose

  clippy:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["kepler/lib", "kepler", "kepler/sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler
    
    - name: Configure rust
      working-directory: ${{ matrix.pkg }}
      run: |
        rustup component add clippy
      
    - name: Clippy
      working-directory: ${{ matrix.pkg }}
      run: RUSTFLAGS="-Dwarnings" cargo clippy

  fmt:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["kepler/lib", "kepler", "kepler/sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler
    
    - name: Configure rust
      working-directory: ${{ matrix.pkg }}
      run: |
        rustup component add rustfmt

    - name: Fmt
      working-directory: ${{ matrix.pkg }}
      run: cargo fmt -- --check
