name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: kepler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler

    - name: Checkout SSI library
      uses: actions/checkout@v2
      with:
        repository: spruceid/ssi
        path: ssi
        ref: 21c13cc96a28c36fa6d1cb8407fc235035fb9f6d
        submodules: true

    - name: Checkout DIDKit library
      uses: actions/checkout@v2
      with:
        repository: spruceid/didkit
        path: didkit
        ref: 436f53baa875564dccf8c04deb57a424290358af
        submodules: true
        
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler
    
    - name: Configure rust
      run: |
        rustup component add clippy
      
    - name: Clippy
      run: RUSTFLAGS="-Dwarnings" cargo clippy

  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
      with:
        path: kepler
    
    - name: Configure rust
      run: |
        rustup component add rustfmt

    - name: Fmt
      run: cargo fmt -- --check
