name: ci

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["lib", ".", "sdk", "sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
    - name: Add WASM target
      if: ${{ matrix.pkg == 'sdk-wasm' }}
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Build
      working-directory: ${{ matrix.pkg }}
      run: cargo build

    - name: Run tests
      if: ${{ matrix.pkg != 'sdk-wasm' }}
      working-directory: ${{ matrix.pkg }}
      run: cargo test

  clippy:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["lib", ".", "sdk", "sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
    - name: Add WASM target
      if: ${{ matrix.pkg == 'sdk-wasm' }}
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Clippy
      working-directory: ${{ matrix.pkg }}
      run: RUSTFLAGS="-Dwarnings" cargo clippy

  fmt:
    strategy:
      fail-fast: false
      matrix:
        pkg: ["lib", ".", "sdk", "sdk-wasm"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kepler repository
      uses: actions/checkout@v2
    - name: Add WASM target
      if: ${{ matrix.pkg == 'sdk-wasm' }}
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Fmt
      working-directory: ${{ matrix.pkg }}
      run: cargo fmt -- --check
